github:
  token: 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  
  repo_owner: OceanKang                  
  repo_name: Githubbot                       

proxy:
  enabled: false                           
  # http: "http://user:pass@proxy:port"    

output:
  csv_path: "./output/github_events.csv"